#!/usr/bin/env python3
"""Generate windows/releases.json from lucy_ws git tags (run at installer build time)."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


def _escape_nsis(text: str) -> str:
    """Escape a string for an NSIS double-quoted argument."""
    return text.replace('$', '$$').replace('"', '$\\"')


def write_nsh(out_nsh: Path, releases: list[dict]) -> None:
    """Emit an NSIS include providing macro LUCY_ADD_RELEASES <combo-handle>."""
    lines = [
        "; Auto-generated by windows/generate_releases.py — do not edit.",
        "!define LUCY_RELEASES_INCLUDED",
        "!macro LUCY_ADD_RELEASES HWND",
    ]
    for rel in releases:
        lines.append(f'  ${{NSD_CB_AddString}} ${{HWND}} "{_escape_nsis(rel["label"])}"')
    lines.append("!macroend")
    out_nsh.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    out = root / "windows" / "releases.json"
    out_nsh = root / "windows" / "releases.nsh"

    try:
        result = subprocess.run(
            ["git", "tag", "-l", "v*"],
            cwd=root,
            capture_output=True,
            text=True,
            check=True,
        )
        tags = sorted(
            [t.strip() for t in result.stdout.splitlines() if t.strip()],
            reverse=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        tags = []

    releases = [
        {
            "id": "latest",
            "label": "Latest (master)",
            "ref": "master",
            "ref_type": "branch",
            "recommended": True,
        }
    ]
    for tag in tags:
        releases.append({
            "id": tag,
            "label": tag,
            "ref": tag,
            "ref_type": "tag",
            "recommended": False,
        })

    payload = {"generated_by": "windows/generate_releases.py", "releases": releases}
    out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {out} ({len(releases)} entries)")

    write_nsh(out_nsh, releases)
    print(f"Wrote {out_nsh} ({len(releases)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
