; Lucy Windows installer (NSIS) — bundles the workspace + Lucy.exe, then runs the
; install via "Lucy.exe --cli ...". NSIS is used (instead of Inno Setup) because
; nsExec::ExecToLog streams the long docker/colcon build output live into the
; installer's details log.
;
; Build: windows/build_installer.ps1 (requires PyInstaller + NSIS / makensis)

Unicode true

!ifndef MyAppVersion
  !define MyAppVersion "0.0.0-dev"
!endif

!define MyAppName "Lucy"
!define MyAppPublisher "Sentience Robotics"
!define MyAppURL "https://github.com/Sentience-Robotics/lucy_ws"
!define MyAppExeName "Lucy.exe"

!define DOC_DOCKER "https://docs.docker.com/desktop/setup/install/windows-install/"
!define DOC_VCXSRV "https://github.com/marchaesen/vcxsrv/releases"
!define DOC_GIT    "https://git-scm.com/install/windows"
!define DOC_PYTHON "https://www.python.org/downloads/"

!include "MUI2.nsh"
!include "nsDialogs.nsh"
!include "LogicLib.nsh"
!include "x64.nsh"

Name "${MyAppName}"
OutFile "..\..\dist\Lucy-Setup-${MyAppVersion}.exe"
InstallDir "$LOCALAPPDATA\Programs\Lucy"
RequestExecutionLevel user
SetCompressor /SOLID lzma
ShowInstDetails show

VIProductVersion "0.0.0.0"
VIAddVersionKey "ProductName" "${MyAppName}"
VIAddVersionKey "ProductVersion" "${MyAppVersion}"
VIAddVersionKey "CompanyName" "${MyAppPublisher}"
VIAddVersionKey "FileDescription" "${MyAppName} Setup"
VIAddVersionKey "FileVersion" "${MyAppVersion}"
VIAddVersionKey "LegalCopyright" "${MyAppPublisher}"

; ----------------------------------------------------------------------------
; State collected from the wizard
; ----------------------------------------------------------------------------
Var InstallMode        ; install | update | repair
Var DeveloperInstall   ; 1 | 0
Var RefreshWorkspace   ; 1 | 0
Var SelectedRef        ; e.g. master or v1.2.3
Var SelectedRefType    ; branch | tag
Var InstallOk          ; 1 only when prereqs + install succeeded

; nsDialogs control handles
Var ModeCombo
Var VersionCombo
Var DevCheck
Var RefreshCheck
Var DockerCheck
Var PrereqText

; ----------------------------------------------------------------------------
; Release list (version dropdown) — generated by windows/generate_releases.py.
; Provides macro LUCY_ADD_RELEASES <combo-handle>. Fallback below if absent.
; ----------------------------------------------------------------------------
!include /NONFATAL "..\releases.nsh"
!ifndef LUCY_RELEASES_INCLUDED
  !macro LUCY_ADD_RELEASES HWND
    ${NSD_CB_AddString} ${HWND} "Latest (master)"
  !macroend
!endif

; ----------------------------------------------------------------------------
; MUI configuration
; ----------------------------------------------------------------------------
!define MUI_ABORTWARNING
!define MUI_ICON "..\assets\lucy-icon.ico"
!define MUI_UNICON "..\assets\lucy-icon.ico"

!define MUI_FINISHPAGE_RUN
!define MUI_FINISHPAGE_RUN_TEXT "Launch Lucy now"
!define MUI_FINISHPAGE_RUN_FUNCTION "LaunchLucy"
!define MUI_FINISHPAGE_LINK "Lucy on GitHub"
!define MUI_FINISHPAGE_LINK_LOCATION "${MyAppURL}"

!insertmacro MUI_PAGE_WELCOME
Page custom ModePageCreate ModePageLeave
!insertmacro MUI_PAGE_DIRECTORY
Page custom OptionsPageCreate OptionsPageLeave
Page custom PrereqPageCreate PrereqPageLeave
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

; ----------------------------------------------------------------------------
; Defaults
; ----------------------------------------------------------------------------
Function .onInit
  StrCpy $InstallMode "install"
  StrCpy $DeveloperInstall "0"
  StrCpy $RefreshWorkspace "1"
  StrCpy $SelectedRef "master"
  StrCpy $SelectedRefType "branch"
  StrCpy $InstallOk "0"
FunctionEnd

; ----------------------------------------------------------------------------
; Page 1 — install mode
; ----------------------------------------------------------------------------
Function ModePageCreate
  !insertmacro MUI_HEADER_TEXT "Install mode" "Choose how to set up Lucy on this machine."
  nsDialogs::Create 1018
  Pop $0
  ${If} $0 == error
    Abort
  ${EndIf}

  ${NSD_CreateLabel} 0 0 100% 12u "Install mode:"
  Pop $1

  ${NSD_CreateDropList} 0 16u 100% 80u ""
  Pop $ModeCombo
  ${NSD_CB_AddString} $ModeCombo "Fresh install"
  ${NSD_CB_AddString} $ModeCombo "Update existing"
  ${NSD_CB_AddString} $ModeCombo "Repair"
  ${NSD_CB_SelectString} $ModeCombo "Fresh install"

  nsDialogs::Show
FunctionEnd

Function ModePageLeave
  ${NSD_GetText} $ModeCombo $0
  ${If} $0 == "Update existing"
    StrCpy $InstallMode "update"
  ${ElseIf} $0 == "Repair"
    StrCpy $InstallMode "repair"
  ${Else}
    StrCpy $InstallMode "install"
  ${EndIf}
FunctionEnd

; ----------------------------------------------------------------------------
; Page 2 — options (version + developer + refresh)
; ----------------------------------------------------------------------------
Function OptionsPageCreate
  !insertmacro MUI_HEADER_TEXT "Options" "Version and developer settings."
  nsDialogs::Create 1018
  Pop $0
  ${If} $0 == error
    Abort
  ${EndIf}

  ${NSD_CreateLabel} 0 0 100% 12u "lucy_ws version:"
  Pop $1

  ${NSD_CreateDropList} 0 16u 100% 80u ""
  Pop $VersionCombo
  !insertmacro LUCY_ADD_RELEASES $VersionCombo
  SendMessage $VersionCombo ${CB_SETCURSEL} 0 0

  ${NSD_CreateCheckbox} 0 44u 100% 12u "Developer install (requires Git; uses SSH clones and DEV mode)"
  Pop $DevCheck

  ${NSD_CreateCheckbox} 0 60u 100% 24u "Download selected lucy_ws version from GitHub (recommended when not using Latest)"
  Pop $RefreshCheck
  ${If} $RefreshWorkspace == "1"
    ${NSD_Check} $RefreshCheck
  ${EndIf}

  nsDialogs::Show
FunctionEnd

Function OptionsPageLeave
  ${NSD_GetState} $DevCheck $0
  ${If} $0 == ${BST_CHECKED}
    StrCpy $DeveloperInstall "1"
  ${Else}
    StrCpy $DeveloperInstall "0"
  ${EndIf}

  ${NSD_GetState} $RefreshCheck $0
  ${If} $0 == ${BST_CHECKED}
    StrCpy $RefreshWorkspace "1"
  ${Else}
    StrCpy $RefreshWorkspace "0"
  ${EndIf}

  ; Derive ref/type from the label. Tag entries use label == ref (ref_type=tag);
  ; the "Latest (master)" entry maps to the master branch.
  ${NSD_GetText} $VersionCombo $0
  StrCpy $1 $0 6
  ${If} $1 == "Latest"
    StrCpy $SelectedRef "master"
    StrCpy $SelectedRefType "branch"
  ${Else}
    StrCpy $SelectedRef $0
    StrCpy $SelectedRefType "tag"
  ${EndIf}
FunctionEnd

; ----------------------------------------------------------------------------
; Page 3 — requirements (scrollable text + confirmation checkbox)
; ----------------------------------------------------------------------------
Function PrereqPageCreate
  !insertmacro MUI_HEADER_TEXT "Requirements" "Scroll for the full list. URLs are selectable; copy one into your browser."

  nsDialogs::Create 1018
  Pop $0
  ${If} $0 == error
    Abort
  ${EndIf}

  StrCpy $PrereqText "Required:$\r$\n  Docker Desktop$\r$\n    ${DOC_DOCKER}$\r$\n  Uncheck $\"Use WSL 2$\" unless you need it for advanced development.$\r$\n  Configure Docker resources to use at least 5 GB RAM.$\r$\n$\r$\nOptional (GUI apps):$\r$\n  VcXsrv$\r$\n    ${DOC_VCXSRV}$\r$\n$\r$\nOptional (developers):$\r$\n  Git for Windows$\r$\n    ${DOC_GIT}$\r$\n  Without Git, repositories are downloaded as ZIP archives.$\r$\n  Python 3$\r$\n    ${DOC_PYTHON}"

  ; Read-only multiline edit; reliably displays/wraps and scrolls if needed.
  ${NSD_CreateMLText} 0 0 100% -22u $PrereqText
  Pop $1
  ${NSD_Edit_SetReadOnly} $1 1

  ${NSD_CreateCheckbox} 0 -18u 100% 12u "Docker Desktop is installed"
  Pop $DockerCheck

  nsDialogs::Show
FunctionEnd

Function PrereqPageLeave
  ${NSD_GetState} $DockerCheck $0
  ${If} $0 != ${BST_CHECKED}
    MessageBox MB_OK|MB_ICONEXCLAMATION "Please confirm that Docker Desktop is installed before continuing."
    Abort
  ${EndIf}
FunctionEnd

; ----------------------------------------------------------------------------
; Prerequisite failure dialog (mirrors the old Inno ShowPrerequisitesFailed)
; ----------------------------------------------------------------------------
Function ShowPrerequisitesFailed
  StrCpy $0 "Required software is missing or not running, so the workspace install was not started.$\r$\n$\r$\nRequired:$\r$\n  Docker Desktop must be installed and running.$\r$\n"
  ${If} $DeveloperInstall == "1"
    StrCpy $0 "$0$\r$\nDeveloper install also requires Git for Windows.$\r$\n"
  ${EndIf}
  StrCpy $0 "$0$\r$\nLucy was copied to your PC. After fixing the items above, run Lucy-Setup.exe again and choose Update.$\r$\n$\r$\nOpen the Docker Desktop install page now?"
  MessageBox MB_YESNO|MB_ICONEXCLAMATION "$0" IDNO +2
  ExecShell "open" "${DOC_DOCKER}"
FunctionEnd

; ----------------------------------------------------------------------------
; Install
; ----------------------------------------------------------------------------
Section "Install"
  SetOutPath "$INSTDIR"
  File "..\..\dist\${MyAppExeName}"
  File "..\..\Dockerfile.humble"
  File "..\..\install.sh"
  File "..\..\launch_lucy.sh"
  File "..\..\Lucy.py"
  File "..\..\README.md"
  File /nonfatal "..\..\*.py"
  File /nonfatal "..\..\*.sh"

  SetOutPath "$INSTDIR\config"
  File /r "..\..\config\*"

  SetOutPath "$INSTDIR\docker"
  File /r "..\..\docker\*"

  SetOutPath "$INSTDIR\windows"
  File /r /x "installer" /x "build_installer.ps1" "..\..\windows\*"

  SetOutPath "$INSTDIR\windows\assets"
  File "..\assets\lucy-icon.ico"

  ; Shortcuts
  CreateDirectory "$SMPROGRAMS\${MyAppName}"
  CreateShortcut "$SMPROGRAMS\${MyAppName}\${MyAppName}.lnk" "$INSTDIR\${MyAppExeName}" "" "$INSTDIR\${MyAppExeName}"
  CreateShortcut "$DESKTOP\${MyAppName}.lnk" "$INSTDIR\${MyAppExeName}" "" "$INSTDIR\${MyAppExeName}"

  ; Add/Remove Programs entry (per-user)
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${MyAppName}" "DisplayName" "${MyAppName}"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${MyAppName}" "DisplayVersion" "${MyAppVersion}"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${MyAppName}" "Publisher" "${MyAppPublisher}"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${MyAppName}" "DisplayIcon" "$INSTDIR\${MyAppExeName}"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${MyAppName}" "UninstallString" "$\"$INSTDIR\Uninstall.exe$\""
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${MyAppName}" "NoModify" 1
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${MyAppName}" "NoRepair" 1

  ; Verify prerequisites before the long-running install.
  SetOutPath "$INSTDIR"
  StrCpy $0 "$\"$INSTDIR\${MyAppExeName}$\" --cli check-prereqs"
  ${If} $DeveloperInstall == "1"
    StrCpy $0 "$0 --developer"
  ${EndIf}
  DetailPrint "Checking prerequisites..."
  nsExec::ExecToLog $0
  Pop $1
  ${If} $1 != 0
    Call ShowPrerequisitesFailed
    DetailPrint "Prerequisites not met — skipped workspace install."
    Goto done
  ${EndIf}

  ; Build the install command line.
  StrCpy $2 "$\"$INSTDIR\${MyAppExeName}$\" --cli $InstallMode --repos-branch master --lucy-ws-ref $SelectedRef --lucy-ws-ref-type $SelectedRefType"
  ${If} $DeveloperInstall == "1"
    StrCpy $2 "$2 --developer"
  ${EndIf}
  ${If} $RefreshWorkspace == "1"
    StrCpy $2 "$2 --refresh-workspace"
  ${EndIf}

  DetailPrint "Running $InstallMode (cloning repos + building Docker image + workspace; this can take a while)..."
  nsExec::ExecToLog $2
  Pop $3
  ${If} $3 == 0
    StrCpy $InstallOk "1"
    DetailPrint "Install completed successfully."
  ${Else}
    MessageBox MB_OK|MB_ICONEXCLAMATION "Install finished with errors (exit code $3). See the log above for details."
  ${EndIf}

  done:
SectionEnd

Function LaunchLucy
  ${If} $InstallOk == "1"
    SetOutPath "$INSTDIR"
    Exec '"$INSTDIR\${MyAppExeName}"'
  ${EndIf}
FunctionEnd

; ----------------------------------------------------------------------------
; Uninstall
; ----------------------------------------------------------------------------
Section "Uninstall"
  Delete "$SMPROGRAMS\${MyAppName}\${MyAppName}.lnk"
  RMDir "$SMPROGRAMS\${MyAppName}"
  Delete "$DESKTOP\${MyAppName}.lnk"
  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${MyAppName}"
  RMDir /r "$INSTDIR"
SectionEnd
